### ISSUE TITLE
the build system does not seem to build sms files (dependencies) for \usemhmodule and \guse

### ISSUE THREAD

**Issue by kohlhase** [UniFormal/MMT#404]
It does for `\importmhmodule` though. They should be handled analogously.
I suspect that `\guse` for `smglom` has the same problem, it should be handled like `\gimport`.

This should be an easy fix. But I do not feel competent in Scala to do it myself.

**Comment by jbetzend** [comment]
Can confirm.

**Comment by jbetzend** [comment]
This should be fixed as of commit 4379a0a. It works fine on my machine now.

**Comment by kohlhase** [comment]
Wonderful, this helps a lot in practice (for new sTeX users).

**Comment by kohlhase** [comment]
Unfortunately, I found a situation, where this is not fixed yet: 
running `mmt make pdflatex` on `.../MathHub/MiKoMH/KWARC/source/admin/fragments/thisdoc-CC-By-SA-NC.tex` which contains 
```
\usemhmodule[repos=MiKoMH/GenCS,path=legal/en/open-content]{creativecommons}
```
will look for the corresponding sms file, but concludes 
```
sms-result: up-to-date /Users/kohlhase/localmh/MathHub/MiKoMH/GenCS/source/legal/en/floss-intro.sms
```
which is clearly wrong,  since this file does not exist. So I guess there is still something wrong.

**Comment by kohlhase** [comment]
In fact, the change breaks sms building: If we use `mmt make sms` on `.../MathHub/MiKoMH/TDM/source/digdocs/en/markup.tex`, which contains 
```
      \usemhmodule[path=digdocs/en/digital-text]{digital-text}%
```
then we get in `markup.sms` 
```
\importmodule[load=/Users/kohlhase/localmh/MathHub/MiKoMH/TDM/source/digdocs/en/digital-text,ext=sms]{digital-text}%
```
which should not be generated. 

So we have to be a bit more careful.

**Comment by jbetzend** [comment]
Curses! Okay, I'm on it!

**Comment by kohlhase** [comment]
great to hear. Good luck

**Comment by jbetzend** [comment]
Fixed as of commit 993b419. (For real this time. We checked!)
